#pipeline Frontend

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  frontendPath: 'Frontend'


steps:

  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
        versionSpec: '20.x'

  - task: Npm@1
    displayName: 'Install Dependencies'
    inputs:
      command: install
      workingDir: '$(frontendPath)'

  - task: Npm@1
    displayName: 'Build Frontend'
    inputs:
      command: custom
      workingDir: '$(frontendPath)'
      customCommand: 'run build'
