#pipeline Frontend


# trigger:
#   branches:
#     include:
#       - main
#   paths:
#     include:
#       - Frontend/*
#     exclude:
#       - '**/*.yml'
#       - '**/*.yalm'

trigger: none

steps:
  - task: UseNode@1
    displayName: Install Node.js
    inputs:
      version: '20.x'

  - task: Npm@1
    displayName: 'Install Dependencies'
    inputs:
      command: install
      workingDir: '$(frontendPath)'

  - task: Npm@1
    displayName: 'Build Frontend'
    inputs:
      command: custom
      workingDir: '$(frontendPath)'
      customCommand: 'run build'
