#pipeline Frontend

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  frontendPath: 'Frontend'


steps:

  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
        versionSpec: '20.x'