
trigger:
- main

# eu nao deveria tbm usar um pool e uma maquina ?
pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/Frontend'
      output_location: 'dist/smt-order-management'
      azure_static_web_apps_api_token: '$(azure-swp-token)'
