
trigger:
- main

variables:
  group: 'swp-variable-group'


pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - task: AzureStaticWebApp@0
    displayName: swp task
    inputs:
      app_location: '/Frontend'
      output_location: 'dist/smt-order-management'
      azure_static_web_apps_api_token: $(azure-swp-token)
