
trigger: none

variables:
  - group: new-variable-group
  - group: swp-variable-group


pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - script: |
      echo "execute comando echo:"
      $(value1)
      echo "Execute comando history:"
      $(value2)
    displayName: Script with Library Test

  - script: |
      echo "show swp token: $(azure-swp-token)"
    displayName: Script Token Test

  - task: AzureStaticWebApp@0
    displayName: SWP task
    inputs:
      app_location: '/Frontend'
      output_location: 'dist/smt-order-management/browser'
      azure_static_web_apps_api_token: $(azure-swp-token)
