#pipeline docker hub


# trigger: none

trigger:
  branches:
    include:
      - main

pool:
    vmImage: 'ubuntu-latest'

variables:
  dockerhubConnectionName: dockerhub-connection

stages:
    - stage: Stage_1
      displayName: Docker Backend
      jobs:
          - job: PublishBackendDockerImage
            steps:
                - checkout: self
                - template: docker-template.yml
                  parameters:
                    repositoryName: 'frotalucas/asmpt-backend-image'
                    dockerhubConnectionName: '$(dockerhubConnectionName)'
                    dockerfilePath: 'Backend/Dockerfile'

    - stage: Stage_2
      displayName: Docker Frontend
      dependsOn: Stage_1
      condition: succeeded()
      jobs:
          - job: PublishFrontendDockerImage
            steps:
                - checkout: self
                - template: docker-template.yml
                  parameters:
                    repositoryName: 'frotalucas/asmpt-frontend-image'
                    dockerhubConnectionName: '$(dockerhubConnectionName)'
                    dockerfilePath: 'Frontend/Dockerfile'