# trigger:
#   branches:
#     include:
#       - main


pool:
  vmImage: 'ubuntu-latest'

variables:
  solutionPath: Backend/asmpt-challenge.sln
  buildConfiguration: Release
  frontendDirectory: Frontend


stages:

  - stage: Stage_1
    displayName: 'backend pipeline'
    jobs:
      - job: RunBackend
        steps:
          - checkout: self
          - template: Backend/asmpt-backend-template.yml


  - stage: Stage_2
    displayName: 'frontend pipeline'
    dependsOn: Stage_1
    condition: succeeded()

    jobs:
      - job: RunFrontend
        steps:
          - checkout: self
          - template: Frontend/asmpt-frontend-template.yml