# trigger:
#   branches:
#     include:
#       - main

trigger: none

pool:
  vmImage: 'ubuntu-latest'



variables:
  #library variables
  - group: 'swp-variable-group'

  # global variables
  - name: dotnetSolutionPath
    value: Backend/asmpt-challenge.sln
  - name: buildConfiguration
    value: Release

  - name: frontendDirectory
    value: Frontend
  - name: frontendOutputPath
    value: dist/smt-order-management/browser
  
  - name: appServiceConnectionName
    value: 'web-app-service-connection'

  # solutionPath: Backend/asmpt-challenge.sln
  # buildConfiguration: Release
  # frontendDirectory: Frontend



stages:

  - stage: Stage_1
    displayName: 'backend pipeline'
    jobs:
      - job: RunBackend
        steps:
          - checkout: self
          - template: Backend/asmpt-backend-template.yml


  - stage: Stage_2
    displayName: 'frontend pipeline'
    dependsOn: Stage_1
    condition: succeeded()

    jobs:
      - job: RunFrontend
        steps:
          - checkout: self
          - template: Frontend/asmpt-frontend-template.yml