

trigger:
  branches:
    include:
      - main



stages:

  - stage: Backend
    displayName: 'Run backend pipeline'
    jobs:
      - job: RunBackend
        steps:
          - checkout: self


  - stage: Frontend
    displayName: 'Run frontend pipeline'
    jobs:
      - job: RunFrontEnd
        steps:
          - checkout: self