

trigger:
  branches:
    include:
      - main



stages:

  - stage: Stage_1
    displayName: 'backend pipeline'
    jobs:
      - job: RunBackend
        steps:
          - checkout: self


  - stage: Stage_2
    displayName: 'frontend pipeline'
    jobs:
      - job: RunFrontEnd
        steps:
          - checkout: self