

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solutionPath: 'Backend/asmpt-challenge.sln'
  buildConfiguration: 'Release'

stages:

  - stage: Stage_1
    displayName: 'backend pipeline'
    jobs:
      - job: RunBackend
        steps:
          - checkout: self
          - template: Backend/asmpt-backend-pipeline.yml


  - stage: Stage_2
    displayName: 'frontend pipeline'
    jobs:
      - job: RunFrontEnd
        steps:
          - checkout: self