trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  FrontendDirectory: Frontend
  SolutionPath: Backend
  BuildConfiguration: Release

stages:
    - stage: First_Stage
      jobs:
          - job: RunFrontend
            displayName: JobFrontend
            steps:
              - checkout: self
              - template: Frontend/test-frontend-tamplate.yml

    - stage: Second_Stage
      jobs:
          - job: RunBackend
            displayName: JobBackend
            steps:
              - checkout: self
              - template: Backend/test-backend-tamplate.yml