trigger:
  - main

pool:
  vmImage: 'Default'  

variables:
  BuildConfiguration: 'Release'
  solutionPath: 'Backend/asmpt-challenge.sln'

steps:
- checkout: self

- script: |
    echo "Hello"
  displayName: 'Print Hello'