trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'  

variables:
  BuildConfiguration: 'Release'
  solutionPath: 'Backend/asmpt-challenge.sln'

steps:
- checkout: self

- script: |
    echo "Hello"
    echo "variable of configuration: $(BuildConfiguration)"
  displayName: 'Script Print Hello'

- script: |
    echo "Working Directory:"
    pwd
    echo "list all files:"
    ls -R
  displayName: 'Script show directory'
